<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXskx4Gj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXskx4Gj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXskx4Gj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXskx4Gj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXskx4Gj\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xskx4Gj',
    'container.build_id' => '0886163f',
    'container.build_time' => 1616763845,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXskx4Gj');
