<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA7qZ2b1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA7qZ2b1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA7qZ2b1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA7qZ2b1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA7qZ2b1\App_KernelDevDebugContainer([
    'container.build_hash' => 'A7qZ2b1',
    'container.build_id' => 'b99df453',
    'container.build_time' => 1618227567,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA7qZ2b1');
